# Nom du pipeline
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linting
        run: |
          pip install flake8
          flake8 bookquest/app --exclude=venv

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      # Changer de répertoire pour accéder au Dockerfile
      - name: Change directory to Dockerfile location
        run: cd ../../

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t bookquest-backend:latest -f Dockerfile .

      # Lancer les tests unitaires
      - name: Run unit tests
        run: docker run --rm -v $(pwd):/app -w /app -e PYTHONPATH=/app/bookquest -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} bookquest-backend:latest pytest ./bookquest/tests/unit

      # Lancer les tests d'intégration
      - name: Run integration tests
        run: docker run --rm -v $(pwd):/app -w /app -e PYTHONPATH=/app/bookquest -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} bookquest-backend:latest pytest ./bookquest/tests/integration

      # Lancer les tests E2E
      - name: Run E2E tests
        run: docker run --rm -v $(pwd):/app -w /app -e PYTHONPATH=/app/bookquest -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} bookquest-backend:latest pytest ./bookquest/tests/e2e

  # Déploiement en staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Change directory to Dockerfile location
        run: cd ../../

      # Construire et pousser l'image Docker pour staging
      - name: Build and push Docker image
        run: |
          docker build -t bookquest-backend:staging -f Dockerfile .
          docker tag bookquest-backend:staging ${{ secrets.DOCKER_HUB_USERNAME }}/bookquest-backend:staging
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bookquest-backend:staging
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment..."

      - name: Run integration tests on Staging
        run: docker run --rm -v $(pwd):/app -w /app -e PYTHONPATH=/app/bookquest -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} bookquest-backend:latest pytest ./bookquest/tests/integration

  # Déploiement en production
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Change directory to Dockerfile location
        run: cd ../../

      # Construire et pousser l'image Docker pour production
      - name: Build and push Docker image
        run: |
          docker build -t bookquest-backend:production -f Dockerfile .
          docker tag bookquest-backend:production ${{ secrets.DOCKER_HUB_USERNAME }}/bookquest-backend:production
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bookquest-backend:production
      - name: Deploy to Production
        run: echo "Deploying to Production environment..."

      - name: Post-deployment tests
        run: docker run --rm -v $(pwd):/app -w /app -e PYTHONPATH=/app/bookquest -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} bookquest-backend:latest pytest ./bookquest/tests/e2e
